/*
 * TIMER1_config.h
 *
 *  Created on: Mar 7, 2022
 *      Author: amrmo
 */

#ifndef MCAL_TIMER1_TIMER1_CONFIG_H_
#define MCAL_TIMER1_TIMER1_CONFIG_H_

// Set Timer Frequancy Here
#define TIMER1_FREQUANCY		(1000UL)

/*
* RANGE :
* 	1 -- > NO_PRESCALER_TIMER_STOP
*	2 -- > PRESCALER_1
*	3 -- > PRESCALER_8
*	4 -- > PRESCALER_64
*	5 -- > PRESCALER_256
*	6 -- > PRESCALER_1024
*	7 -- > EXTERNAL_CLK_FALLING_EDGE
*	8 -- > EXTERNAL_CLK_RISING_EDGE
*/
#define TIMER1_PRESCALER		PRESCALER_8
/*
 * RANGE:
 * 1 -- >  TIMER1_PRESCALER_VAL_1
 * 2 -- >  TIMER1_PRESCALER_VAL_8
 * 3 -- >  TIMER1_PRESCALER_VAL_64
 * 4 -- >  TIMER1_PRESCALER_VAL_256
 * 5 -- >  TIMER1_PRESCALER_VAL_1024
 */
#define TIMER1_PRESCALER_VALUE	TIMER1_PRESCALER_VAL_8

/*
 * RAGNE:
 * 	1 -- >   NORMAL_MODE     	                   9 -- > 	 PWM_PHASE_AND_FREQUANCY_CORRECT_ICR_TOP
* 	2 -- >   PWM_PHASE_CORRECT_8BIT                10 -- >   PWM_PHASE_AND_FREQUANCY_CORRECT_OCR_TOP
 * 	3 -- >   PWM_PHASE_CORRECT_9BIT                11 -- >   PWM_PHASE_CORRECT_ICR_TOP
 * 	4 -- >   PWM_PHASE_CORRECT_10BIT               12 -- >   PWM_PHASE_CORRECT_OCR_TOP
 * 	5 -- >   CTC_MODE_OCR_TOP                      13 -- >   CTC_MODE_ICR_TOP
 * 	6 -- >   FAST_PWM_8BIT                         14 -- >   FAST_PWM_ICR_TOP
 * 	8 -- >   FAST_PWM_9BIT                         15 -- >   FAST_PWM_OCR_TOP
 * 	7 -- >   FAST_PWM_10BIT
 */
#define TIMER1_WAVE_GEN_MODE	NORMAL_MODE

/*
 * RANGE:
 * 	A) NON_PWM MODE
 * 		1 -- > NORMAL_MODE
 * 		2 -- > TOGGLE_OC1A_ON_COMPARE_MATCH
 * 		3 -- > CLEAR_OC1A_ON_COMPARE_MATCH
 * 		4 -- > SET_OC1A_ON_COMPARE_MATCH
 * 	B) PWM MODES
 * 		1 -- > NORMAL_MODE
 * 		2 -- > TOGGLE_OC1A_ON_COMPARE_MATCH
 * 		3 -- > CLEAR_OC1A_ON_COMPARE_MATCH
 * 		4 -- > SET_OC1A_ON_COMPARE_MATCH
 */
#define TIMER1_COMPA_OUTPUT_MODE	NORMAL_MODE


/*
 * RANGE:
 * 	A) NON_PWM MODE
 * 		1 -- > NORMAL_MODE
 * 		2 -- > TOGGLE_OC1B_ON_COMPARE_MATCH
 * 		3 -- > CLEAR_OC1B_ON_COMPARE_MATCH
 * 		4 -- > SET_OC1B_ON_COMPARE_MATCH
 * 	B) PWM MODES
 * 		1 -- > NORMAL_MODE
 * 		2 -- > CLEAR_OC1B_ON_COMPARE_MATCH
 * 		3 -- > SET_OC1B_ON_COMPARE_MATCH
 */
#define TIMER1_COMPB_OUTPUT_MODE	NORMAL_MODE



#endif /* MCAL_TIMER1_TIMER1_CONFIG_H_ */
