/*
 * TIMER2_config.h
 *
 *  Created on: Mar 14, 2022
 *      Author: amrmo
 */

#ifndef MCAL_TIMER2_TIMER2_CONFIG_H_
#define MCAL_TIMER2_TIMER2_CONFIG_H_


#define TIMER2_CLOCK_FREQUANCY	(8000UL)

/*
 * RANGE:
 *  - TIMER2_NO_CLOCK_SOURCE
 *  - TIMER2_PRESCALER_1
 *  - TIMER2_PRESCALER_8
 *  - TIMER2_PRESCALER_32
 *  - TIMER2_PRESCALER_64
 *  - TIMER2_PRESCALER_128
 *  - TIMER2_PRESCALER_256
 *  - TIMER2_PRESCALER_1024
 */
#define TIMER2_PRESCALER	TIMER2_PRESCALER_8

/*
 * RANGE:
 *  - TIMER2_NO_CLOCK_SOURCE
 *  - TIMER2_PRESCALER_VALUE_1
 *  - TIMER2_PRESCALER_VALUE_8
 *  - TIMER2_PRESCALER_VALUE_32
 *  - TIMER2_PRESCALER_VALUE_64
 *  - TIMER2_PRESCALER_VALUE_128
 *  - TIMER2_PRESCALER_VALUE_256
 *	- TIMER2_PRESCALER_VALUE_1024
 */
#define TIMER2_PRESCALER_VALUE	TIMER2_PRESCALER_VALUE_8

/*
 * RANGE:
 *  - TIMER2_NON_PWM_MODE
 *  - TIMER2_FAST_PWM_MODE
 *  - TIMER2_CTC_MODE
 *  - TIMER2_PHASE_CORRECT_PWM_MODE
 */
#define TIMER2_WAVE_GENERATON_MODE	TIMER2_NON_PWM_MODE

/*
 * RANGE:
 * 	(1) for non-PWM mode
 * 		- TIMER2_NORMAL
 * 		- TIMER2_TOGGLE_OC2
 * 		- TIMER2_SET_OC2
 * 		- TIMER2_CLEAR_OC2
 * 	(2) for PWM modes
 * 		- TIMER2_PWM_NORMAL
 * 		- TIMER2_PWM_SET_OC2
 * 		- TIMER2_PWM_CLEAR_OC2
 */
#define TIMER2_COMPARE_OUTPUT_MODE	TIMER2_NORMAL


#endif /* MCAL_TIMER2_TIMER2_CONFIG_H_ */
